/*
 * 文案集中模块(铁律 #1:中文单语,i18n 结构预留)。
 * 结构按 namespace 分组,未来接 i18n 库时整体下沉为 zh-CN.json 即可。
 * 键名用英文语义命名,值一律中文。
 */

export const strings = {
  app: {
    name: 'AutoAnime',
    tagline: '本地优先的三级识别追番管线',
  },

  nav: {
    dashboard: '总览',
    pipeline: '管线',
    library: '媒体库',
    subscriptions: '追番',
    rssSources: 'RSS 源',
    pending: '待确认',
    logs: '日志',
    settings: '设置',
    collapse: '收起侧栏',
    expand: '展开侧栏',
  },

  theme: {
    toDark: '切换到深色',
    toLight: '切换到浅色',
  },

  common: {
    loading: '加载中…',
    retry: '重试',
    cancel: '取消',
    confirm: '确认',
    save: '保存',
    saving: '保存中…',
    delete: '删除',
    remove: '移除',
    close: '关闭',
    submit: '提交',
    add: '添加',
    edit: '编辑',
    enable: '启用',
    disable: '停用',
    enabled: '已启用',
    disabled: '已停用',
    prevPage: '上一页',
    nextPage: '下一页',
    pageInfo: '第 {current} / {total} 页',
    total: '共 {count} 条',
    empty: '暂无数据',
    loadFailed: '加载失败',
    actionFailed: '操作失败',
    unknown: '未知',
    never: '从未',
    yes: '是',
    no: '否',
    copied: '已复制',
    rollback: '撤销整理',
    rollbackConfirm: '确认撤销这次整理?文件将按 reverse instruction 回到原位。',
    rolledBack: '已撤销',
  },

  dashboard: {
    title: '总览',
    manualInterventionRate: '人工介入率',
    weeklyArchived: '本周归档',
    llmCallRate: 'LLM 调用率',
    weeklyArchivedUnit: '集',
    pendingQueue: '待确认队列',
    pendingQueueUnit: '条',
    levelHits: '三级管线命中',
    l1High: 'L1 高置信',
    l2Hit: 'L2 记忆命中',
    l3Entered: 'L3 进入',
    llmCalls: 'LLM 调用',
    weeklyCurve: '近 7 日曲线',
    archived: '归档',
    llmCallsShort: 'LLM 调用',
    pending: '待确认',
    totalParsed: '累计解析',
  },

  library: {
    title: '媒体库',
    searchPlaceholder: '搜索标题…',
    seasons: '季',
    episodes: '集',
    seasonN: '第 {n} 季',
    episodeN: '第 {n} 集',
    episodeShort: 'E{n}',
    qualityScore: '质量分',
    upgradedCount: '已洗版',
    airDate: '放送日期',
    filePath: '文件路径',
    noFilePath: '未归档',
    state: {
      missing: '缺集',
      downloading: '下载中',
      downloaded: '已下载',
      organized: '已归档',
      upgraded: '已洗版',
      ignored: '已忽略',
    },
    seasonState: {
      upcoming: '未放送',
      airing: '放送中',
      ended: '已完结',
      collected: '已收藏',
    },
    mediaType: {
      tv: 'TV',
      movie: '剧场版',
      ova: 'OVA',
      special: '特别篇',
    },
    empty: '媒体库为空。添加订阅后,归档的剧集会出现在这里。',
  },

  subscriptions: {
    title: '追番',
    addSubscription: '添加订阅',
    rssUrl: 'Mikan RSS 地址',
    rssUrlPlaceholder: 'https://mikanani.me/RSS/MyBangumi?token=…',
    submitAdd: '订阅',
    progress: '放送进度',
    collectedOfAired: '已收 {collected} / 已放 {aired} / 全 {total} 集',
    nextAirDate: '下次放送',
    fansubPref: '字幕组',
    noFansub: '未指定',
    mikanHint: '每番只订一个字幕组',
    mikanEntry: '去 Mikan 选番',
    state: {
      upcoming: '未放送',
      airing: '放送中',
      ended: '已完结',
      collected: '已收藏',
    },
    reducedFrequency: '已降频',
    reducedFrequencyHint: '完结收藏后每月仅检查洗版机会',
    removeConfirm: '确认取消订阅「{title}」?已归档文件不受影响。',
    empty: '还没有订阅。从 Mikan 选番或粘贴 RSS 地址开始追番。',
    addFailed: '订阅失败',
    urlRequired: '请填写 RSS 地址',
  },

  rssSources: {
    title: 'RSS 源',
    addSource: '添加源',
    url: '地址',
    season: '关联季',
    lastPolledAt: '上次拉取',
    token: '令牌(可选)',
    tokenHint: 'RSS token 按密钥处理,不会出现在日志里',
    addSubmit: '添加',
    urlRequired: '请填写源地址',
    removeConfirm: '确认移除该 RSS 源?',
    empty: '没有 RSS 源。订阅会自动创建对应源,也可以手动添加。',
    pollNever: '从未拉取',
  },

  pending: {
    title: '待确认',
    queueHint: '低置信度解析结果在此排队。每一次纠正都会沉淀进记忆,下次不再打扰。',
    rawName: '原始文件名',
    stage: '来源阶段',
    reason: '原因',
    createdAt: '提交时间',
    parsedFields: '解析结果(逐字段标注证据来源)',
    evidence: {
      name: '文件名',
      folder: '目录',
      memory: '记忆',
      llm: 'LLM',
    },
    confidence: '置信度',
    confirmAction: '按此结果确认',
    correctAction: '纠正',
    rejectAction: '拒绝',
    correctFormTitle: '纠正解析结果',
    correctFormHint: '提交后将触发学习:写入解析记忆与别名,同类文件直接命中。',
    fieldTitle: '标题',
    fieldSeason: '季',
    fieldEpisode: '集',
    fieldFansub: '字幕组',
    fieldResolution: '分辨率',
    submitCorrect: '提交纠正',
    empty: '队列为空,没有需要人工确认的解析结果。',
    resolved: '已处理',
  },

  pipeline: {
    title: '管线',
    subtitle: '三级识别 → 仲裁 → 归档,实时文件流',
    node: {
      input: '输入',
      l1: 'L1 本地解析',
      l2: 'L2 规则记忆',
      l3: 'L3 LLM 兜底',
      arbiter: '仲裁',
      organize: '归档',
      pending: '人工确认',
    },
    nodeDesc: {
      input: 'RSS / 手动导入',
      l1: 'anitopy 方言解析',
      l2: '记忆 + 别名修正',
      l3: '低置信度才调用',
      arbiter: '置信度路由',
      organize: '重命名 / 洗版',
      pending: '低置信度队列',
    },
    badge: {
      hitRate: '命中率',
      entered: '进入',
      passed: '通过',
      calls: '调用',
    },
    flow: {
      live: '实时',
      offline: '未连接',
      file: '文件流',
      clear: '清空记录',
      recent: '最近事件',
    },
    empty: '等待第一个文件进入管线…',
  },

  logs: {
    title: '日志',
    groupByOperation: '按操作分组',
    operationId: '操作',
    entity: '对象',
    action: '动作',
    actor: '执行者',
    actorAuto: '自动',
    actorManual: '手动',
    time: '时间',
    instruction: 'instruction',
    reverse: 'reverse',
    expandGroup: '展开 {n} 条记录',
    collapseGroup: '收起',
    rollbackAction: '撤销整理',
    rollbackOnlyOrganize: '仅整理类操作可撤销',
    empty: '还没有审计日志。',
    filterPlaceholder: '搜索操作 ID / 对象…',
  },

  settings: {
    title: '设置',
    downloaderSection: '下载器',
    client: '下载客户端',
    clientQbittorrent: 'qBittorrent',
    clientAria2: 'aria2',
    downloaderUrl: '下载器地址',
    llmSection: 'LLM',
    llmEnabled: '启用 LLM 兜底',
    llmEnabledHint: '关闭后,低置信度结果全部进入人工确认队列',
    llmModel: '模型',
    autonomySection: '自主权限',
    autonomyHint: '管线的自动决策尺度;保守档全部转人工',
    autonomy: {
      low: '保守:每次人工确认',
      medium: '均衡:低置信转人工',
      high: '自动:仅冲突转人工',
    },
    qualitySection: '质量与洗版',
    upgradeThreshold: '洗版触发阈值(新分 ≥ 现分 + 阈值)',
    maxUpgrades: '单集洗版上限(次)',
    copyPolicy: '跨盘降级策略',
    copyPolicyCopy: '允许 copy',
    copyPolicyStrict: 'strict:永不 copy',
    skipSizeGb: '单文件跳过上限(GB)',
    saved: '已保存',
    saveFailed: '保存失败',
  },

  sse: {
    connected: '事件流已连接',
    connecting: '事件流连接中…',
    disconnected: '事件流已断开',
    reconnecting: '正在重连(第 {attempt} 次)…',
  },

  error: {
    title: '出错了',
    back: '返回',
  },
} as const

export type Strings = typeof strings

/** 简易插值:'第 {n} 季' + {n: 2} → '第 2 季' */
export function t(template: string, vars: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in vars ? String(vars[key]) : match,
  )
}
