/*
 * 文案集中模块(铁律 #1:中文单语,i18n 结构预留)。
 * 结构按 namespace 分组,未来接 i18n 库时整体下沉为 zh-CN.json 即可。
 * 键名用英文语义命名,值一律中文。
 */

export const strings = {
  app: {
    name: 'AutoAnime',
    tagline: '本地优先的三级识别追番管线',
  },

  nav: {
    dashboard: '总览',
    pipeline: '管线',
    library: '媒体库',
    subscriptions: '追番',
    rssSources: 'RSS 源',
    pending: '待确认',
    logs: '日志',
    settings: '设置',
    collapse: '收起侧栏',
    expand: '展开侧栏',
  },

  theme: {
    toDark: '切换到深色',
    toLight: '切换到浅色',
  },

  common: {
    loading: '加载中…',
    retry: '重试',
    cancel: '取消',
    confirm: '确认',
    save: '保存',
    saving: '保存中…',
    delete: '删除',
    remove: '移除',
    close: '关闭',
    submit: '提交',
    add: '添加',
    edit: '编辑',
    enable: '启用',
    disable: '停用',
    enabled: '已启用',
    disabled: '已停用',
    prevPage: '上一页',
    nextPage: '下一页',
    pageInfo: '第 {current} / {total} 页',
    total: '共 {count} 条',
    empty: '暂无数据',
    loadFailed: '加载失败',
    actionFailed: '操作失败',
    unknown: '未知',
    never: '从未',
    yes: '是',
    no: '否',
    copied: '已复制',
    rollback: '撤销整理',
    rollbackConfirm: '确认撤销这次整理?文件将按 reverse instruction 回到原位。',
    rolledBack: '已撤销',
  },

  dashboard: {
    title: '总览',
    manualInterventionRate: '人工介入率',
    auditManual: '人工',
    auditTotal: '总审计',
    pendingQueue: '待确认队列',
    pendingQueueUnit: '条待人工确认',
    llmCallRate: 'LLM 调用率',
    levelHits: '三级管线统计',
    levelL1: 'L1 本地解析',
    levelL2: 'L2 记忆命中',
    levelL3: 'L3 LLM 兜底',
    llmCallsShort: 'LLM 调用',
    weeklyCurve: 'LLM 调用周曲线',
    episodeStates: '库内集状态分布',
    noData: '暂无数据',
  },

  library: {
    title: '媒体库',
    searchPlaceholder: '搜索标题…',
    seasons: '季',
    episodes: '集',
    seasonN: '第 {n} 季',
    episodeN: '第 {n} 集',
    episodeShort: 'E{n}',
    qualityScore: '质量分',
    upgradedCount: '已洗版',
    airDate: '放送日期',
    filePath: '文件路径',
    noFilePath: '未归档',
    state: {
      missing: '缺集',
      downloading: '下载中',
      downloaded: '已下载',
      organized: '已归档',
      upgraded: '已洗版',
      ignored: '已忽略',
    },
    seasonState: {
      upcoming: '未放送',
      airing: '放送中',
      ended: '已完结',
      collected: '已收藏',
    },
    mediaType: {
      tv: 'TV',
      movie: '剧场版',
      ova: 'OVA',
      special: '特别篇',
    },
    empty: '媒体库为空。添加订阅后,归档的剧集会出现在这里。',
  },

  subscriptions: {
    title: '追番',
    addSubscription: '添加订阅',
    titleLabel: '标题(至少填一个语言的标题)',
    titlePlaceholder: '如:葬送的芙莉莲',
    titleRequired: '请填写标题',
    seasonNumber: '季号',
    episodeCount: '当季集数(可选)',
    episodeCountPlaceholder: '留空不预生成集表',
    submitAdd: '订阅',
    fansubPref: '字幕组偏好',
    fansubPlaceholder: '如:Kamigakari',
    noFansub: '未指定',
    rssHint: '先在这里建订阅,再在「RSS 源」页把 Mikan RSS 地址挂到对应季',
    mikanHint: '每番只订一个字幕组',
    mikanEntry: '去 Mikan 选番',
    organizedOfTotal: '已归档 {organized}/{total} 集',
    missingCount: '缺 {count} 集',
    rssCount: 'RSS 源 {count}',
    noSeasons: '暂无季信息',
    removeConfirm: '确认取消订阅「{title}」?已归档文件不受影响。',
    empty: '还没有订阅。先添加一个标题开始追番。',
    addFailed: '订阅失败',
    removeFailed: '取消订阅失败',
  },

  rssSources: {
    title: 'RSS 源',
    addSource: '添加源',
    url: '地址',
    season: '关联季',
    seasonHint: '必填:从订阅列表选择要挂载的季',
    seasonPlaceholder: '请选择关联季',
    seasonEmptyOption: '暂无可选季,请先在「追番」页创建订阅',
    seasonOption: '{title} · 第 {n} 季(ID {id})',
    seasonRequired: '请选择关联季',
    lastPolledAt: '上次拉取',
    token: '令牌(可选)',
    tokenHint: 'RSS token 按密钥处理,不会出现在日志里',
    addSubmit: '添加',
    urlRequired: '请填写源地址',
    removeConfirm: '确认移除该 RSS 源?',
    empty: '没有 RSS 源。订阅会自动创建对应源,也可以手动添加。',
    toggleFailed: '启停源失败',
    removeFailed: '移除源失败',
  },

  pending: {
    title: '待确认',
    queueHint: '低置信度解析结果在此排队。每一次纠正都会沉淀进记忆,下次不再打扰。',
    rawName: '原始文件名',
    stage: '来源阶段',
    reason: '原因',
    createdAt: '提交时间',
    parsedFields: '解析草稿(来自管线写入的 context)',
    confirmAction: '按此结果确认',
    correctAction: '纠正',
    rejectAction: '拒绝',
    correctFormTitle: '纠正解析结果',
    correctFormHint: '标题必填;提交后触发学习:写入解析记忆与别名,同类文件直接命中。',
    fieldTitle: '标题',
    fieldSeason: '季',
    fieldEpisode: '集',
    fieldSegment: '段落类型',
    fieldFansub: '字幕组',
    segment: {
      episode: '单集',
      season_pack: '整季包',
      movie: '剧场版',
    },
    submitCorrect: '提交纠正',
    empty: '队列为空,没有需要人工确认的解析结果。',
    resolved: '已处理',
    quickConfirm: '确认',
    batchConfirm: '批量确认',
    batchReject: '批量拒绝',
    batchConfirmAsk: '确认 {n} 条？',
    batchRejectAsk: '拒绝 {n} 条？',
    selectedCount: '已选 {n} 条',
    selectAll: '全选本页',
    selectRow: '选择 {name}',
    clearSelection: '取消选择',
    batchPartialFailed: '{n} 条处理失败,已保留在队列中,可重试',
  },

  pipeline: {
    title: '管线',
    subtitle: '三级识别 → 仲裁 → 归档,实时文件流',
    flowSteps: '流程步骤',
    node: {
      input: '输入',
      l1: 'L1 本地解析',
      l2: 'L2 规则记忆',
      l3: 'L3 LLM 兜底',
      arbiter: '仲裁',
      organize: '归档',
      pending: '人工确认',
    },
    nodeDesc: {
      input: 'RSS / 手动导入',
      l1: 'anitopy 方言解析',
      l2: '记忆 + 别名修正',
      l3: '低置信度才调用',
      arbiter: '置信度路由',
      organize: '重命名 / 洗版',
      pending: '低置信度队列',
    },
    badge: {
      hitRate: '命中率',
      entered: '进入',
      passed: '通过',
      calls: '调用',
    },
    flow: {
      live: '实时',
      offline: '未连接',
      file: '文件流',
      clear: '清空记录',
      recent: '最近事件',
    },
    empty: '等待第一个文件进入管线…',
  },

  logs: {
    title: '日志',
    groupByOperation: '按操作分组',
    operationId: '操作',
    entity: '对象',
    action: '动作',
    actor: '执行者',
    actorAuto: '自动',
    actorManual: '手动',
    time: '时间',
    instruction: 'instruction',
    reverse: 'reverse',
    expandGroup: '展开 {n} 条记录',
    collapseGroup: '收起',
    rollbackAction: '撤销整理',
    rollbackOnlyOrganize: '仅整理类操作可撤销',
    rollbackHint: '按该组最新审计行执行撤销;无可回滚 reverse 指令时后端返回 409',
    empty: '还没有审计日志。',
    filterPlaceholder: '搜索操作 ID / 对象…',
    rollbackConfirmCount: '撤销这 {n} 条操作？',
  },

  settings: {
    title: '设置',
    runtimeHint: 'PUT 仅覆写本进程运行时项,重启后回到 env/toml 配置',
    runtimeSection: '运行时开关',
    dryRun: '试运行模式',
    dryRunHint: '开启后只做识别与计划,不实际移动文件',
    l2Enabled: 'L2 记忆命中',
    l2EnabledHint: '关闭后解析不查解析记忆',
    llmEnabled: '启用 LLM 兜底',
    llmEnabledHint: '关闭后,低置信度结果全部进入人工确认队列',
    llmModel: '模型',
    referenceEnabled: '参考链回填',
    referenceEnabledHint: 'confirm/correct 时经参考源回填别名',
    referenceOrder: '参考源顺序',
    referenceOrderHint: '逗号分隔,如:bangumi,tmdb',
    environmentSection: '环境信息(只读)',
    libraryPath: '媒体库路径',
    downloadPath: '下载目录',
    apiEndpoint: 'API 地址',
    sseHeartbeat: 'SSE 心跳间隔',
    sseReplay: 'SSE 重放上限',
    apiToken: 'API Token',
    apiTokenInput: 'API Token(本端注入)',
    apiTokenHint: '后端设置 AUTOANIME_API_TOKEN 时,请求需携带同值(X-API-Token 头;SSE 走 ?token=)。保存在浏览器 localStorage,保存/清除后刷新页面生效',
    apiTokenSave: '保存 Token',
    apiTokenClear: '清除 Token',
    apiTokenSavedNotice: '已保存,刷新页面后生效',
    apiTokenClearedNotice: '已清除,刷新页面后生效',
    llmApiKey: 'LLM API Key',
    configured: '已配置',
    notConfigured: '未配置',
    secretHint: '密钥不回显,只显示是否已配置',
    qualitySection: '质量与洗版',
    e4Hint: '依赖 E4 的持久化设置表',
    e4Unavailable: '洗版阈值与命名模板将在 E4 落地后开放配置,当前版本不提供。',
    saved: '已保存',
    saveFailed: '保存失败',
  },

  sse: {
    connected: '事件流已连接',
    connecting: '事件流连接中…',
    disconnected: '事件流已断开',
    reconnecting: '正在重连(第 {attempt} 次)…',
  },

  error: {
    title: '出错了',
    back: '返回',
  },
} as const

export type Strings = typeof strings

/** 简易插值:'第 {n} 季' + {n: 2} → '第 2 季' */
export function t(template: string, vars: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in vars ? String(vars[key]) : match,
  )
}
