/*
 * 文案集中模块(铁律 #1:中文单语,i18n 结构预留)。
 * 结构按 namespace 分组,未来接 i18n 库时整体下沉为 zh-CN.json 即可。
 * 键名用英文语义命名,值一律中文。
 */

export const strings = {
  app: {
    name: 'AutoAnime',
    tagline: '本地优先的三级识别追番工具',
    mockMode: 'Mock 数据模式',
    mockBanner:
      '当前展示的是内置 Mock 演示数据，不是真实媒体库。仅显式设置 VITE_USE_MOCK=1 时才会进入该模式；去掉该变量（或设为 0）即连回真实后端。',
  },

  nav: {
    dashboard: '总览',
    pipeline: '导入与识别',
    library: '媒体库',
    subscriptions: '追番',
    rssSources: 'RSS 源',
    pending: '待确认',
    logs: '日志',
    settings: '设置',
    collapse: '收起侧栏',
    expand: '展开侧栏',
  },

  theme: {
    toDark: '切换到深色',
    toLight: '切换到浅色',
  },

  common: {
    loading: '加载中…',
    retry: '重试',
    cancel: '取消',
    confirm: '确认',
    confirmTitle: '请确认',
    save: '保存',
    saving: '保存中…',
    delete: '删除',
    remove: '移除',
    close: '关闭',
    submit: '提交',
    add: '添加',
    edit: '编辑',
    enable: '启用',
    disable: '停用',
    enabled: '已启用',
    disabled: '已停用',
    prevPage: '上一页',
    nextPage: '下一页',
    pageInfo: '第 {current} / {total} 页',
    total: '共 {count} 条',
    empty: '暂无数据',
    loadFailed: '加载失败',
    actionFailed: '操作失败',
    unknown: '未知',
    never: '从未',
    yes: '是',
    no: '否',
    copied: '已复制',
    rollback: '撤销整理',
    rollbackConfirm: '确认撤销这次整理?文件将按 reverse instruction 回到原位。',
    rolledBack: '已撤销',
  },

  dashboard: {
    title: '总览',
    manualInterventionRate: '周期人工介入率',
    auditManual: '人工',
    auditTotal: '总审计',
    pendingQueue: '待确认队列',
    pendingQueueUnit: '条待人工确认',
    llmCallRate: 'LLM 调用率',
    levelHits: '三级识别统计',
    levelL1: 'L1 本地解析',
    levelL2: 'L2 记忆命中',
    levelL3: 'L3 LLM 兜底',
    llmCallsShort: 'LLM 调用',
    weeklyCurve: 'LLM 调用周曲线',
    episodeStates: '库内集状态分布',
    noData: '暂无数据',
  },

  library: {
    title: '媒体库',
    searchPlaceholder: '搜索标题…',
    seasons: '季',
    episodes: '集',
    seasonN: '第 {n} 季',
    episodeN: '第 {n} 集',
    episodeShort: 'E{n}',
    qualityScore: '质量分',
    upgradedCount: '已洗版',
    airDate: '放送日期',
    filePath: '文件路径',
    noFilePath: '未归档',
    state: {
      missing: '缺集',
      downloading: '下载中',
      downloaded: '已下载',
      organized: '已归档',
      upgraded: '已洗版',
      ignored: '已忽略',
      flagged: '异常',
    },
    seasonState: {
      upcoming: '未放送',
      airing: '放送中',
      ended: '已完结',
      collected: '已收藏',
    },
    mediaType: {
      tv: 'TV',
      movie: '剧场版',
      ova: 'OVA',
      special: '特别篇',
    },
    empty: '媒体库为空。添加订阅后,归档的剧集会出现在这里。',
  },

  subscriptions: {
    title: '追番',
    addSubscription: '添加订阅',
    titleLabel: '标题(至少填一个语言的标题)',
    titlePlaceholder: '如:葬送的芙莉莲',
    titleRequired: '请填写标题',
    seasonNumber: '季号',
    episodeCount: '当季集数(可选)',
    episodeCountPlaceholder: '留空不预生成集表',
    submitAdd: '订阅',
    edit: '编辑',
    editTitle: '编辑订阅',
    status: '状态',
    statusActive: '连载中',
    statusPaused: '暂停',
    statusFinished: '完结',
    qualityPref: '质量偏好',
    optionalClearHint: '清空并保存 = 清除该偏好',
    editSaved: '已保存',
    fansubPref: '字幕组偏好',
    fansubPlaceholder: '如:Kamigakari',
    noFansub: '未指定',
    rssHint: '先在这里建订阅,再在「RSS 源」页把 Mikan RSS 地址挂到对应季',
    mikanHint: '每番只订一个字幕组',
    mikanEntry: '去 Mikan 选番',
    organizedOfTotal: '已归档 {organized}/{total} 集',
    missingCount: '缺 {count} 集',
    rssCount: 'RSS 源 {count}',
    noSeasons: '暂无季信息',
    removeConfirm: '确认取消订阅「{title}」?已归档文件不受影响。',
    empty: '还没有订阅。先添加一个标题开始追番。',
    addFailed: '订阅失败',
    removeFailed: '取消订阅失败',
    searchPlaceholder: '搜索本季番剧…',
    searchEmpty: '没有匹配的番剧',
    regionAll: '全部',
    regionJp: '日漫',
    regionCn: '国漫',
    regionKr: '韩漫',
    regionUs: '美漫',
    showSpecials: '特别篇(OVA/ONA)',
    showNoCn: '无中文翻译',
    sortLabel: '排序',
    sortByAir: '放送日期',
    sortByRating: '评分',
    filterCount: '共 {n} 部',
    filterHidden: '已隐藏 {m} 部',
    badgeSubscribed: '已订阅',
    ruleInclude: '必须包含关键词',
    ruleExclude: '必须排除关键词',
    rulePlaceholder: '分号分隔,如:简中;B-Global',
    ruleHint: 'include 非空=白名单;exclude 命中即拒绝;大小写不敏感',
    previewBtn: '匹配预览',
    previewing: '预览中…',
    previewSummary: '{total} 条中 {dl} 条会被下载(同集只取评分最优第一条)',
    previewWouldDownload: '将下载',
    previewCandidate: '备选',
    previewRejected: '已排除',
    previewUnparsed: '未识别',
    previewFailed: '预览失败:请检查 RSS 地址后重试',
  },

  rssSources: {
    title: 'RSS 源',
    addSource: '添加源',
    url: '地址',
    season: '关联季',
    seasonHint: '必填:从订阅列表选择要挂载的季',
    seasonPlaceholder: '请选择关联季',
    seasonEmptyOption: '暂无可选季,请先在「追番」页创建订阅',
    seasonOption: '{title} · 第 {n} 季(ID {id})',
    seasonRequired: '请选择关联季',
    lastPolledAt: '上次拉取',
    token: '令牌(可选)',
    tokenHint: 'RSS token 按密钥处理,不会出现在日志里',
    editTitle: '编辑 RSS 源',
    tokenUnchangedHint: '留空 = 不修改已有 token',
    clearToken: '清除 Token',
    editSaved: '已保存',
    addSubmit: '添加',
    urlRequired: '请填写源地址',
    removeConfirm: '确认移除该 RSS 源?',
    empty: '没有 RSS 源。订阅会自动创建对应源,也可以手动添加。',
    toggleFailed: '启停源失败',
    removeFailed: '移除源失败',
  },

  pending: {
    title: '待确认',
    queueHint: '低置信度解析结果在此排队。每一次纠正都会沉淀进记忆,下次不再打扰。',
    rawName: '原始文件名',
    stage: '来源阶段',
    reason: '原因',
    createdAt: '提交时间',
    parsedFields: '解析草稿(来自识别流程写入的 context)',
    confirmAction: '按此结果确认',
    correctAction: '纠正',
    rejectAction: '拒绝',
    correctFormTitle: '纠正解析结果',
    correctFormHint: '标题必填;提交后触发学习:写入解析记忆与别名,同类文件直接命中。',
    fieldTitle: '标题',
    fieldSeason: '季',
    fieldEpisode: '集',
    fieldSegment: '段落类型',
    fieldFansub: '字幕组',
    segment: {
      episode: '单集',
      season_pack: '整季包',
      movie: '剧场版',
    },
    submitCorrect: '提交纠正',
    empty: '队列为空,没有需要人工确认的解析结果。',
    resolved: '已处理',
    quickConfirm: '确认',
    batchConfirm: '批量确认',
    batchReject: '批量拒绝',
    batchConfirmAsk: '确认 {n} 条？',
    batchRejectAsk: '拒绝 {n} 条？',
    selectedCount: '已选 {n} 条',
    selectAll: '全选本页',
    selectRow: '选择 {name}',
    clearSelection: '取消选择',
    batchPartialFailed: '{n} 条处理失败,已保留在队列中,可重试',
    // 12-F:拒绝可填 reason(后端 PendingRejectIn.reason 可选)
    rejectReasonLabel: '拒绝原因(可选)',
    rejectReasonPlaceholder: '留空则不记录原因',
    confirmReject: '确认拒绝',
  },

  pipeline: {
    title: '导入与识别',
    subtitle: '文件名的识别、确认与归档,全程实时记录',
    flowSteps: '流程步骤',
    node: {
      input: '输入',
      l1: 'L1 本地解析',
      l2: 'L2 规则记忆',
      l3: 'L3 LLM 兜底',
      arbiter: '仲裁',
      organize: '归档',
      pending: '人工确认',
    },
    nodeDesc: {
      input: 'RSS / 手动导入',
      l1: 'anitopy 方言解析',
      l2: '记忆 + 别名修正',
      l3: '低置信度才调用',
      arbiter: '置信度路由',
      organize: '重命名 / 洗版',
      pending: '低置信度队列',
    },
    badge: {
      hitRate: '命中率',
      entered: '进入',
      passed: '通过',
      calls: '调用',
    },
    flow: {
      live: '实时',
      offline: '未连接',
      file: '文件流',
      clear: '清空记录',
      recent: '最近事件',
    },
    empty: '等待第一个文件进入识别流程…',
    manualSection: '手动操作',
    parseName: '单文件解析试跑',
    parseNameHint: 'L1 本地解析,不访问网络、不写数据库',
    parsePickHint: '选文件后自动回填所在目录/父目录,可再手改',
    parsePreview: '试跑解析',
    importDirectory: '导入目录',
    autoScanHint: 'qB 自带 RSS 下载器等外部下载源落在本目录的文件,会由调度器定时扫描:命中已有订阅的自动归档进媒体库,其余忽略(AUTOANIME_LIBRARY_AUTOSCAN_ENABLED 可关)',
    dryRun: 'Dry run',
    startImport: '开始导入',
    runOnce: '跑一轮订阅闭环',
    running: '执行中…',
    completed: '已完成',
    failed: '已失败',
    processedOfTotal: '{processed}/{total}',
    // 12-F:parse-preview 补 folder/parent 可选上下文;run-once scope 三选
    parseFolder: '所在目录(可选)',
    parseFolderHint: '文件所在目录的名称,如 Season 1,辅助 L1 判断季与段落类型',
    parseParent: '父目录路径(可选)',
    parseParentHint: '包含该文件的完整目录路径,如 D:\\downloads\\番剧\\Show\\Season 1,确认后归档据此还原来源',
    parseFolderPlaceholder: 'Season 1',
    parseParentPlaceholder: 'D:\\downloads\\番剧\\Show\\Season 1',
    schedulerScopeLabel: '执行范围',
    schedulerScopeAll: '全部',
    schedulerScopeRss: '仅 RSS 轮询',
    schedulerScopeDownload: '仅下载对账',
  },

  logs: {
    title: '日志',
    groupByOperation: '按操作分组',
    operationId: '操作',
    entity: '对象',
    action: '动作',
    actor: '执行者',
    actorAuto: '自动',
    actorManual: '手动',
    time: '时间',
    instruction: 'instruction',
    reverse: 'reverse',
    expandGroup: '展开 {n} 条记录',
    collapseGroup: '收起',
    rollbackAction: '撤销整理',
    rollbackOnlyOrganize: '仅整理类操作可撤销',
    rollbackHint: '按该组最新审计行执行撤销;无可回滚 reverse 指令时后端返回 409',
    empty: '还没有审计日志。',
    filterPlaceholder: '搜索操作 ID / 对象…',
    rollbackConfirmCount: '撤销这 {n} 条操作？',
    // 12-F:组展开明细行的行级撤销(POST /api/organize/{audit_id}/rollback 接受任意行 id)
    rollbackRow: '撤销此条',
    rollbackRowConfirm: '确认撤销审计行 #{id} 的操作？',
    rollbackRowDone: '已撤销审计行 #{id}',
    copyOperationId: '复制操作 ID',
  },

  settings: {
    title: '设置',
    runtimeHint: '配置已持久化保存;按改动类型分三档生效:立即 / 调度重建后 / 重启后,保存时逐项提示',
    unsavedLeaveConfirm: '有未保存的更改,确定离开吗?',
    runtimeSection: '运行时开关',
    dryRun: '试运行模式',
    dryRunHint: '开启后只做识别与计划,不实际移动文件',
    l2Enabled: 'L2 记忆命中',
    l2EnabledHint: '关闭后解析不查解析记忆',
    llmEnabled: '启用 LLM 兜底',
    llmEnabledHint: '关闭后,低置信度结果全部进入人工确认队列',
    llmModel: '模型',
    referenceEnabled: '参考链回填',
    referenceEnabledHint: 'confirm/correct 时经参考源回填别名',
    referenceOrder: '参考源顺序',
    referenceOrderHint: '逗号分隔,如:bangumi,tmdb',
    environmentSection: '环境信息(只读)',
    libraryPath: '媒体库路径',
    downloadPath: '下载目录',
    apiEndpoint: 'API 地址',
    sseHeartbeat: 'SSE 心跳间隔',
    sseReplay: 'SSE 重放上限',
    apiToken: 'API Token',
    apiTokenInput: 'API Token(本端注入)',
    apiTokenHint: '后端设置 AUTOANIME_API_TOKEN 时,请求需携带同值(X-API-Token 头;SSE 走 ?token=)。保存在浏览器 localStorage,保存/清除后即时生效,事件流会自动重连',
    apiTokenSave: '保存 Token',
    apiTokenClear: '清除 Token',
    apiTokenSavedNotice: '已保存,后续请求即时生效',
    apiTokenClearedNotice: '已清除,后续请求即时生效',
    llmApiKey: 'LLM API Key',
    configured: '已配置',
    notConfigured: '未配置',
    secretHint: '密钥不回显,只显示是否已配置',
    qualitySection: '质量与洗版',
    e4Hint: '依赖 E4 的持久化设置表',
    e4Unavailable: '洗版阈值与命名模板将在 E4 落地后开放配置,当前版本不提供。',
    saved: '已保存',
    saveFailed: '保存失败',
    // ---- 12-E:配置中心 Tabs(七标签页) ----
    tabs: {
      runtime: '运行',
      identify: '识别',
      downloader: '下载器',
      upgrade: '洗版',
      scheduler: '调度',
      notify: '通知',
      env: '环境',
    },
    dirtyDot: '{tab}有未保存更改',
    logLevel: '日志级别',
    logLevelHint: '进程日志输出级别',
    llmBaseUrl: 'LLM Base URL',
    llmBaseUrlHint: '重启后生效',
    llmTimeout: 'LLM 超时(秒)',
    llmMaxRetries: 'LLM 最大重试',
    referenceQps: '参考源 QPS',
    referenceQpsHint: '留空 = 不限速',
    tmdbApiKey: 'TMDB API Key',
    downloaderKind: '下载器',
    qbHost: 'qBittorrent 地址',
    qbPort: 'qBittorrent 端口',
    qbUser: 'qBittorrent 用户名',
    qbPassword: 'qBittorrent 密码',
    testQbit: '测试连接',
    qbitTesting: '测试中…',
    qbitTestOk: 'qBittorrent 连接成功',
    qbitTestFail: 'qBittorrent 连接失败',
    upgradeThreshold: '洗版触发阈值',
    upgradeMaxPerEpisode: '单集洗版上限',
    upgradeCopyPolicy: '洗版覆盖策略',
    copyPolicyAllow: 'allow(允许覆盖)',
    copyPolicyStrict: 'strict(仅升级)',
    upgradeSkipSizeGb: '跳过洗版体积(GB)',
    mismatchBackfillBudget: '错配回填预算',
    namingTitleLanguage: '命名标题语言',
    namingTitleLanguageHint: '如 zh/jp/romaji',
    schedulerEnabled: '调度器启用',
    rssPollInterval: 'RSS 轮询间隔(分钟)',
    rssPollJitter: 'RSS 轮询抖动(%)',
    downloadPollInterval: '下载对账间隔(秒)',
    downloadMaxRetries: '下载最大重试',
    collectedCheckDays: '完结检查周期(天)',
    pendingBacklogThreshold: '待确认积压告警阈值',
    schedulerHint: '调度类字段保存后自动生效(调度循环重建)',
    notifyEnabled: '启用通知',
    notifyWebhookUrl: 'Webhook 地址',
    notifyTelegramToken: 'Telegram Bot Token',
    notifyTelegramChatId: 'Telegram Chat ID',
    testNotify: '发送测试通知',
    notifyTesting: '发送中…',
    notifyTestOk: '测试通知已发送',
    notifyTestFail: '测试通知发送失败',
    secretPlaceholderConfigured: '已配置,留空保持不变',
    secretPlaceholderNotConfigured: '未配置',
    clearSecret: '清除已配置值',
    effectImmediate: '已生效',
    effectScheduler: '已生效(调度已重建)',
    effectRestart: '重启后生效',
    warningsTitle: '部分变更产生警告',
    notifyTestNoChannels: '未配置任何通知通道',
    rssFetchTimeout: 'RSS 抓取超时(秒)',
    rssFetchRetries: 'RSS 抓取重试',
  },

  sse: {
    connected: '事件流已连接',
    connecting: '事件流连接中…',
    disconnected: '事件流已断开',
    reconnecting: '正在重连(第 {attempt} 次)…',
    // Layout 顶部 SseBanner(与状态行文案区分:带数据可能过期提示)
    bannerClosed: '事件流已断开,页面数据可能不是最新。',
    bannerReconnecting: '事件流连接中断,正在重连…(第 {attempt} 次)',
  },

  error: {
    title: '出错了',
    back: '返回',
  },

  // ---- 12-F 收尾:RSS 立即轮询 / 人工确认命名 / 集重新识别 / 识别指标 ----
  ops12f: {
    // RssSources 行内「立即轮询」(POST /api/rss_sources/{id}/poll)
    pollAction: '立即轮询',
    pollDone: '轮询完成:拾取 {picked} 条新条目,本轮下载完成 {completed} 个',
    pollSkipped: '未到计划轮询时间,本次已跳过',
    pollFetchError: '源拉取失败',
    pollDisabled: '源已停用,请先启用',
    pollConflict: '已有轮询在进行,请稍后再试',
    pollFailed: '轮询失败',
    // Pipeline「人工确认命名」卡片(POST /api/pipeline/confirm-name)
    confirmNameTitle: '人工确认命名',
    confirmNameHint: '教系统认识一种命名:填入一个文件名并给出正确的标题/季/集/字幕组拆解,确认后写入识别记忆——之后同类命名不再询问、直接命中。适用于:某类命名解析错误或低置信,想一次性教会系统。',
    confirmExampleBtn: '填入示例',
    confirmNameFileHint: '要教系统认识的原始文件名(可照示例改成自己的)',
    confirmTitleHint: '该文件名实际对应的作品名(与媒体库一致)',
    confirmNameField: '文件名',
    confirmNameRequired: '请填写文件名',
    confirmNameOptionalHint: '留空 = 回退识别草稿',
    confirmNameSegmentEmpty: '由识别流程判断',
    submitConfirmName: '确认并学习',
    confirmNameDone: '已写入识别记忆 {entries} 条,下次同类命名直接命中',
    confirmNameArchived: '已归档到 {dst}',
    confirmNameNotArchived: '未归档:{reason}',
    // Library 集「重新识别」(POST /api/episodes/{id}/reparse 两步契约)
    reparseAction: '重新识别',
    reparsePreviewTitle: '重新识别预览',
    reparsePreviewHint: '按当前文件名重跑三级识别。确认执行后将重命名并移动文件,请核对目标路径。',
    reparseOriginal: '原文件',
    reparseParsedTitle: '识别标题',
    reparseSeasonEpisode: '识别季集',
    reparseTargetPath: '目标路径',
    reparseNoParsed: '未能解析出识别结果(目标路径仍按库内季集生成)',
    reparseSkip: '目标位守卫命中,无需移动',
    reparseConfirm: '确认执行',
    reparseConfirmDialog: '确认重新识别并移动该文件?文件将按目标路径重命名移动。',
    reparseDone: '重新识别完成,已归档到 {dst}',
    // Dashboard「识别指标」区块(GET /api/report,CLI report --json 同构)
    reportTitle: '识别指标',
    reportHint: '累计统计,与 CLI report --json 同口径(区别于上方的周期指标)',
    reportParsed: '累计解析',
    reportLlmFallback: 'LLM 兜底',
    reportLlmRate: 'LLM 调用率',
    reportArchived: '归档事件',
    reportManual: '人工纠正',
    reportInterventionRate: '人工介入率',
    reportLoadFailed: '识别指标加载失败',
  },

  // ---------- 12-UX 修复批(2026-09-08):各页人性化补缺;键由主会话统一维护 ----------
  uxfix: {
    parseNameRequired: '请先输入要试跑的文件名',
    importPathRequired: '请先输入要导入的目录路径',
    parsePreviewTitle: '试跑结果',
    parsePreviewEmpty: '未能解析出有效字段;这类命名建议在「待确认」页人工纠正后学习',
    importProgress: '已处理 {done}/{total}',
    savedSummary: '已保存 {n} 项',
    savedImmediate: '{n} 项立即生效',
    savedRebuild: '{n} 项调度重建后生效',
    savedRestart: '{n} 项重启后生效',
    savedWarnings: '有 {n} 条警告,请留意',
    settingsChangedElsewhere: '配置已被其它窗口修改,请刷新页面后再保存',
    unitMinute: '分钟',
    unitSecond: '秒',
    unitPercent: '%',
    unitTimes: '次',
    unitGb: 'GB',
    numberRangeHint: '允许范围 {min} ~ {max}',
    emptyRssCta: '去「追番」创建订阅',
    emptyPendingCta: '去「导入与识别」试跑一个文件名',
    emptyLibraryHint: '添加订阅并完成导入后,归档的剧集会出现在这里',
    onboardingTitle: '三步开始使用',
    selectionKept: '已保留跨页选择的 {n} 条',
    batchInvalidRemoved: '{n} 条已失效,已从选择中移除',
    previewConfidenceLabel: '置信度',
    previewVerdictLabel: '裁决',
    verdictHigh: 'HIGH:自动归档',
    verdictMedium: 'MEDIUM:待确认',
    verdictLow: 'LOW:建议人工',
    showRawJson: '查看原始 JSON',
    // ---------- 12-IA 重构(2026-09-09):选番页/目录选择器;键由主会话统一维护 ----------
    seasonBrowse: '季度选番',
    mySubscriptions: '我的订阅',
    manageRss: '管理 RSS 源',
    rssSourcesAdvancedHint: 'RSS 源的高级管理入口;日常订阅在「追番」页选番即可',
    seasonCurrent: '当季',
    seasonDegraded: '该季度数据暂时不可用,请稍后再试',
    subscribeAndAttach: '订阅并挂 RSS',
    subscribeOnly: '仅订阅(RSS 稍后再挂)',
    fansubOptionalHint: '字幕组偏好(可选);不知道选什么就先留空',
    mikanSearch: '在 Mikan 搜索',
    subscribeSuccess: '订阅成功,可去「媒体库」查看',
    drawerRssHint: 'Mikan 番剧 RSS 或任意通用 RSS(如 PT 站 API 源)均可;通用源请先用「匹配预览」验证命中',
    onboardingStep1: '① 在「追番」页按季度选番,一键订阅',
    onboardingStep2: '② qBittorrent 下载完成后自动入库(或在「导入与识别」页手动导入)',
    onboardingStep3: '③ 在「媒体库」查看归档与洗版',
    pickerTitle: '选择目录',
    pickerTitleFile: '选择文件',
    pickerChoose: '选择当前目录',
    pickerEmpty: '此目录下没有子目录',
    pickerFileEmpty: '此目录下没有文件',
    pickerSelectFile: '选择',
    selectFileBtn: '选择文件',
    selectDirBtn: '选择目录',
    pickerDrives: '此电脑',
    subscribeAdopted: '已存在同名订阅,已合并到现有条目',
    // ---------- 12-IA 追加(P1-E 信息架构重构):季节切换条/选番卡片/订阅抽屉 ----------
    seasonPickerLabel: '选番周期',
    seasonNames: {
      winter: '冬季',
      spring: '春季',
      summer: '夏季',
      fall: '秋季',
    },
    mikanAutoFetchTitle: '从 Mikan 自动获取字幕组 RSS',
    mikanAutoFetchFailed: 'Mikan 获取失败,可手动粘贴 RSS',
    mikanAutoFetchEmpty: 'Mikan 未找到匹配番剧,可手动粘贴 RSS',
    mikanGroupSelected: '已选:{name}',
    seasonGridEmpty: '该季度暂无条目',
    ratingLabel: '评分',
    ratingScore: '{score} 分',
    rssNotSaved: '订阅成功,但 RSS 源未挂载成功,请到「管理 RSS 源」检查地址后重试',
    // ---------- 12-UX P1 修复批(2026-09-09) ----------
    subscribeOnlySuccess: '订阅成功。可在「我的订阅」顶部「管理 RSS 源」挂上 RSS 后自动下载',
    onboardingStep2Note: '需先在「设置→下载器」配置 qBittorrent',
    episodesUnknown: '集数未知',
    notAired: '尚未放送',
  },
} as const

export type Strings = typeof strings

/** 简易插值:'第 {n} 季' + {n: 2} → '第 2 季' */
export function t(template: string, vars: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in vars ? String(vars[key]) : match,
  )
}
